### PR TITLE
Displaying artworks and exhibitions pages

### LINKED ISSUE #15: [4pt]  - Display list of items on the Homepage - Student A
Create the main part of the homepage that keeps the layout from the wireframe: 

Screenshot 2021-06-27 at 21 50 23

When the page loads, the webapp retrieves data from  the selected API and shows the list of items on screen with the basic data (e.g. title + image).

Prepare also "Comments" and "Reservations" buttons. They should be doing nothing - just being displayed.

This task **does not** include displaying the number of likes for each item.

This task **does not** include the counter of the items.

### LINKED ISSUE #16: [0.5pt] Add footer - group task
Create footer according to the wireframe: 

Screenshot 2021-06-27 at 21 42 29

### LINKED ISSUE #17: [0.5pt] Add header - group task
Create page header according to the wireframe:

Screenshot 2021-06-27 at 21 42 24

### PR DESCRIPTION
**Pull request by fmanimashaun**
## Artwork Displaying artworks and exhibitions pages:

The following were achieved:

- Create the page navigations
- Create the page footer
- Create the artworks (home page) layout while calling data from the API
- Create the exhibition layout while calling data from the API
- Create the overall site styling using sass

### CODE REVIEW

**Review by francis3400 — APPROVED** [review]
- [ ]  Good implementations 
- [ ] Good Layout and API calls
- [ ]  Nice commit messages


Congratulations 👌👌😎😎, there is nothing else to do than to merge.

**Comment by gealsanchez** [comment]
Hi @fmanimashaun , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

✅ Correct use of Gitflow
✅ No linter error
✅ README is okay
✅ Good PR Description 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

- [ OPTIONAL] Please fix the broken link of the image in the LiveDemo section of the README file, thanks

**Comment by fmanimashaun** [comment]
> * [ ]   Good implementations
> * [ ]  Good Layout and API calls
> * [ ]   Nice commit messages
> 
> Congratulations 👌👌😎😎, there is nothing else to do than to merge.

Thanks for the comments!

**Review by gealsanchez — APPROVED** [review]
Hi @fmanimashaun , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

✅ Correct use of Gitflow
✅ No linter error
✅ README is okay
✅ Good PR Description 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

- [ OPTIONAL] Please fix the broken link of the image in the LiveDemo section of the README file, thanks

**Comment by fmanimashaun** [comment]
> Hi @fmanimashaun ,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
>  [ 68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f6b69674c7466447256334b394e307759434f2f67697068792e676966 ](https://camo.githubusercontent.com/3d609eecb3c7a59d1c7e987f145222671b61ac2da3bb0707e5e5eb33d5a7842e/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f6b69674c7466447256334b394e307759434f2f67697068792e676966) [ ](https://camo.githubusercontent.com/3d609eecb3c7a59d1c7e987f145222671b61ac2da3bb0707e5e5eb33d5a7842e/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f6b69674c7466447256334b394e307759434f2f67697068792e676966)
> 
> ## Highlights
> ✅ Correct use of Gitflow ✅ No linter error ✅ README is okay ✅ Good PR Description 👍
> 
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> * [ OPTIONAL] Please fix the broken link of the image in the LiveDemo section of the README file, thanks



> Hi @fmanimashaun ,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
>  [ 68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f6b69674c7466447256334b394e307759434f2f67697068792e676966 ](https://camo.githubusercontent.com/3d609eecb3c7a59d1c7e987f145222671b61ac2da3bb0707e5e5eb33d5a7842e/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f6b69674c7466447256334b394e307759434f2f67697068792e676966) [ ](https://camo.githubusercontent.com/3d609eecb3c7a59d1c7e987f145222671b61ac2da3bb0707e5e5eb33d5a7842e/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f6b69674c7466447256334b394e307759434f2f67697068792e676966)
> 
> ## Highlights
> ✅ Correct use of Gitflow ✅ No linter error ✅ README is okay ✅ Good PR Description 👍
> 
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> * [ OPTIONAL] Please fix the broken link of the image in the LiveDemo section of the README file, thanks

Thanks for your kind remarks! The broken images has been fixed as shown below:

image

**Pull request merged**
